modLoader = "javafml"
loaderVersion = "${forge_loader_version_range}"
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
description = "${description}"
authors = "${mod_authors}"
logoFile = "assets/${mod_id}/icon.png"

[[mixins]]
config = "instantbackup.mixins.json"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_loader_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${compatible_mc_version_range}"
ordering = "NONE"
side = "BOTH"
