# General Properties
java_version=17
minecraft_version=1.20.1
compatible_mc_version_range=[1.20,1.21)

# Fabric-specific Properties
fabric_loader=0.19.3
fabric_api_version=0.92.9+1.20.1

# NeoForge-specific Properties
neoforge_loader=47.1.105

# Forge-specific Properties
forge_loader=47.4.20
forge_loader_version_range=[47,)

# Selected loaders (comma-separated: fabric, neoforge, forge)
builds_for=fabric,neoforge,forge
