# General Properties
java_version=21
minecraft_version=26.1
compatible_mc_versions=["26.1"]
forge_loader_version_range=[0,)

# Fabric-specific Properties
fabric_loader=0.19.3
fabric_api_version=0.153.0+26.1.2

# Selected loaders
builds_for=fabric
