# General Properties
java_version=25
minecraft_version=26.2
compatible_mc_version_range=[26.1,26.3)

# Fabric-specific Properties
fabric_loader=0.19.3
fabric_api_version=0.153.0+26.2

# NeoForge-specific Properties
neoforge_loader=26.2.0.7-beta

# Forge-specific Properties
forge_loader=65.0.1
forge_loader_version_range=[65,)

# Selected loaders (comma-separated: fabric, neoforge, forge)
builds_for=fabric,neoforge,forge
